/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kolanot.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the InvoicePayment service. Represents a row in the &quot;kolanot_InvoicePayment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.kolanot.service.model.impl.InvoicePaymentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.kolanot.service.model.impl.InvoicePaymentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InvoicePayment
 * @generated
 */
@ProviderType
public interface InvoicePaymentModel extends BaseModel<InvoicePayment> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a invoice payment model instance should use the {@link InvoicePayment} interface instead.
	 */

	/**
	 * Returns the primary key of this invoice payment.
	 *
	 * @return the primary key of this invoice payment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this invoice payment.
	 *
	 * @param primaryKey the primary key of this invoice payment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the invoice payment ID of this invoice payment.
	 *
	 * @return the invoice payment ID of this invoice payment
	 */
	public long getInvoicePaymentId();

	/**
	 * Sets the invoice payment ID of this invoice payment.
	 *
	 * @param invoicePaymentId the invoice payment ID of this invoice payment
	 */
	public void setInvoicePaymentId(long invoicePaymentId);

	/**
	 * Returns the transactionid of this invoice payment.
	 *
	 * @return the transactionid of this invoice payment
	 */
	@AutoEscape
	public String getTransactionid();

	/**
	 * Sets the transactionid of this invoice payment.
	 *
	 * @param transactionid the transactionid of this invoice payment
	 */
	public void setTransactionid(String transactionid);

	/**
	 * Returns the invoice ID of this invoice payment.
	 *
	 * @return the invoice ID of this invoice payment
	 */
	public long getInvoiceId();

	/**
	 * Sets the invoice ID of this invoice payment.
	 *
	 * @param invoiceId the invoice ID of this invoice payment
	 */
	public void setInvoiceId(long invoiceId);

}